language: python
python:
    - "2.7"
script: nosetests
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
install:
    - pip install pyparsing epydoc sphinx nose pyside --use-mirrors
    - make build
notifications:
    email: false
