language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
install:
    - pip install pyparsing
    - make build
script:
    - pytest -vv --rootdir=./
